version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "ecommerce"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  server:
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    expose:
      - "8080"
